# -*- coding: utf-8 -*-
"""karnataka-agriculture-eda-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQRVpByKRAYk0bYQwZp4lFJBGg-JqygN
"""

!pip install klib

import numpy as np
import pandas as pd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
from matplotlib.ticker import MaxNLocator
import seaborn as sns
import plotly.express as px
import warnings
warnings.simplefilter('ignore')
import klib
from tqdm import tqdm
import os
from plotly.offline import init_notebook_mode
init_notebook_mode(connected = True)
import plotly.io as pio

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

data = pd.read_csv('/content/data_season.csv')
df = pd.DataFrame(data)
display(df.head(5))

print(f'the dataset shape is row: {df.shape[0]} - column: {df.shape[1]}')

df.dtypes

df.info()

columns = df.select_dtypes(include = 'object')
for i in columns:
    print(f'{i}:')
    print(df[i].value_counts())
    print('\n')

df2 = df.drop_duplicates()
print(f'dataset shape after removal is {df2.shape} and main dataset shape is {df.shape}')

describe = df2.describe(include='all')
describe.style.background_gradient(cmap='coolwarm')

columns2 = df.select_dtypes(include = 'object')
for col in columns2:
    print(f'{col}:{pd.unique(df[col])}')
    print('\n')

for col in df.columns:
    print(repr(col))

df['Year'] = pd.to_datetime(df['Year'],format = '%Y')
df['Year'] = df['Year'].dt.year
df.sort_values(by=['Year'], ascending = True, inplace = True)
df.reset_index(inplace = True, drop = True)
df

klib.corr_mat(df2)

"""1. **Area**:
   - **Skewness**: 2.03 (Right-skewed distribution with most values concentrated on the left side).
   - **Standard Deviation**: 15,180.47 (High variability in data).
   - **Kurtosis**: 2.80 (Moderate peakness).

2. **Humidity**:
   - **Skewness**: -0.30 (Slight left-skew, indicating concentration around the mean).
   - **Standard Deviation**: 2.47 (Low variability, data is consistent).
   - **Kurtosis**: -0.61 (Slightly flat distribution).

3. **Price**:
   - **Skewness**: 0.73 (Slight right-skew with two noticeable modes).
   - **Standard Deviation**: 94,123.16 (Very high variability).
   - **Kurtosis**: -1.24 (Flatter distribution with moderate tails).

4. **Rainfall**:
   - **Skewness**: -1.60 (Significant left-skew, indicating concentration on the right).
   - **Standard Deviation**: 1,163.83 (Moderate variability).
   - **Kurtosis**: 0.94 (Near-normal peak).

5. **Temperature**:
   - **Skewness**: 1.36 (Right-skewed with some higher extreme values).
   - **Standard Deviation**: 60.81 (Moderate variability).
   - **Kurtosis**: 0.17 (Close to normal distribution).

6. **Year**:
   - **Skewness**: 0.15 (Nearly symmetric distribution).
   - **Standard Deviation**: 5.10 (Low variability, values are tightly clustered).
   - **Kurtosis**: -1.50 (Relatively flat distribution).

7. **Yields**:
   - **Skewness**: 5.20 (Strongly right-skewed with extreme outliers).
   - **Standard Deviation**: 58,228.99 (High variability).
   - **Kurtosis**: 39.86 (Heavy-tailed distribution).

## Key Insights
- **Skewness** and **Kurtosis** reveal the shape and extremity of the distributions:
  - Right-skewed distributions: Area, Yields, Temperature.
  - Left-skewed distributions: Rainfall, Humidity.
- **Standard Deviation** highlights variability:
  - High variability: Area, Yields, Price.
  - Low variability: Humidity, Year.
- **Special Notes**:
  - Multimodal distributions: Price (indicates distinct groups).
  - Extreme values and outliers are prominent in Yields.
"""

columnss = df.select_dtypes(include = ['number']).columns
for col in columnss:
    klib.dist_plot(df[col])
    plt.savefig(col)
    plt.show()

columnss = df.select_dtypes(include = ['number']).columns
i = 0
while i < 6:
    fig = plt.figure(figsize=(15,2))
    plt.subplot(1,2,1)
    sns.boxplot(x = columnss[i], data = df, color = 'blue')


    i+=1
    plt.subplot(1,2,2)
    sns.boxplot(x = columnss[i], data = df, color = 'gray')


    i+=1
    plt.savefig(columnss[i])
    plt.show()

"""
## **1. Year by Location**
- The year data shows a consistent spread across locations, with a few minor variations.
- There are no significant outliers, and the median year is stable.

## **2. Area by Location**
- Wide variability is observed, with some locations showing extremely high outliers (e.g., one location above 50,000).
- Central values vary significantly across locations.

## **3. Rainfall by Location**
- Data is tightly clustered around the median across all locations.
- Minor outliers exist below 1,000 in a few locations, but overall variability is low.

## **4. Temperature by Location**
- A few locations exhibit high variability and outliers extending above 200.
- Most locations have tightly clustered temperature values.

## **5. Humidity by Location**
- Humidity values are consistently distributed across locations.
- Medians are very close, indicating uniform conditions.

## **6. Yields by Location**
- Yields show significant variability with outliers extending to very high values in certain locations.
- Some locations display tighter distributions with lower yields.

## **7. Price by Location**
- Price data is fairly consistent across locations, with a few outliers.
- The interquartile range (IQR) is similar, and medians do notsignificant variation.

---

## **Key Insights**
1. **Outliers**:
   - Outliers are prominent in "Area" and "Yields" datasets, indicating potential data points that warrant further investigation.
2. **Uniformity**:
   - "Humidity" and "Rainfall" datasets are consistent across locations, suggesting stable environmental conditions.
3. **Variability**:
   - "Temperature" and "Area" show location-dependent variability, why indicate regional differences.

---

This analysis highlights key patterns and anomalies acoss the datasets for different locations.
"""

column = df.select_dtypes(include = 'number').columns
plt.subplots(4,2, figsize = (25,25))
for idx, col in tqdm(enumerate(column), total = len(column), desc = 'plotting...:'):
    plt.subplot(4,2,idx + 1)
    sns.boxplot(x='Location', y=col, data=df)
    plt.tick_params(axis = 'x', labelsize = 16)
    plt.tick_params(axis = 'y', labelsize = 16)
    plt.title(f'Box Plot of {col} by Location', fontsize = 18, fontweight = 'bold')
    plt.xlabel('Location', fontsize = 16, fontweight = 'bold')
    plt.ylabel(col, fontsize = 16, fontweight = 'bold')
    plt.xticks(rotation=15)
    plt.savefig(col,)
plt.subplots_adjust(left=0.1, bottom=0.1, right=0.9, top=0.9, wspace=0.15, hspace=7.5)
plt.tight_layout()
plt.show()

"""
## **1. Year by Soil Type**
- Year data shows consistent distribution across most soil types, with slight variations.
- Medians are stable, with no significant outliers.

## **2. Area by Soil Type**
- Significant variability in area, with some soil types showing extreme outliers exceeding 50,000.
- Some soil types have tightly clustered areas, while others show a wide spread.

## **3. Rainfall by Soil Type**
- Most soil types have tightly clustered rainfall data.
- Some outliers exist below 1,000 for certain soil types.

## **4. Temperature by Soil Type**
- Temperature distributions vary widely across soil types.
- A few soil types exhibit high outliers above 200.

## **5. Humidity by Soil Type**
- Humidity is consistently distributed across all soil types.
- Medians are nearly identical, indicating stable environmental conditions.

## **6. Yields by Soil Type**
- Significant variability in yields, with numerous outliers exceeding 100,000 in many soil types.
- Certain soil types have tighter distributions with lower yield values.

## **7. Price by Soil Type**
- Prices show minimal variation across soil types, with a few minor outliers.
- Medians and interquartile ranges (IQRs) are similar across all soil types.

---

## **Key Insights**
1. **Outliers**:
   - Outliers are prevalent in "Area" and "Yields" datasets, especially in certain soil types.
2. **Uniformity**:
   - "Humidity" and "Rainfall" data exhibit consistent patterns across all soil types.
3. **Variability**:
   - Significant variability is observed in "Temperature" and "Area" based on soil types, which may indicate soil-specific influences.

---

This analysis highlights key patterns and anomalies across the datasets for different soil types.
"""

column = df.select_dtypes(include = 'number').columns
plt.subplots(4,2, figsize = (25,25))
for idx, col in tqdm(enumerate(column), total = len(column), desc = 'plotting...:'):
    plt.subplot(4,2,idx + 1)
    sns.boxplot(x='Soil type', y=col, data=df)
    plt.tick_params(axis = 'x', labelsize = 16)
    plt.tick_params(axis = 'y', labelsize = 16)
    plt.title(f'Box Plot of {col} by Soil type', fontsize = 22, fontweight = 'bold')
    plt.xlabel('Soil type	', fontsize = 16, fontweight = 'bold')
    plt.ylabel(col, fontsize = 16, fontweight = 'bold')
    plt.xticks(rotation=90)
plt.savefig(col)
plt.subplots_adjust(left=0.1, bottom=0.1, right=0.9, top=0.9, wspace=0.15, hspace=7.5)
plt.tight_layout()
plt.show()

"""
## **1. Year by Irrigation Type**
- Year data is consistent across all irrigation types, with no significant outliers.
- Medians are stable across "Drip," "Basin," and "Spray" irrigation types.

## **2. Area by Irrigation Type**
- Significant variability in area, with extreme outliers exceeding 50,000 for all irrigation types.
- Central areas are similar across irrigation types, though variability is slightly higher in the "Spray" type.

## **3. Rainfall by Irrigation Type**
- Rainfall values are tightly clustered around the median for all irrigation types.
- Minor outliers exist below 1,000 for "Drip" and "Spray" irrigation types.

## **4. Temperature by Irrigation Type**
- "Spray" irrigation exhibits very low temperature values, with no significant variability.
- "Drip" and "Basin" irrigation types show higher temperatures, with outliers extending above 200.

## **5. Humidity by Irrigation Type**
- Humidity is consistently distributed across all irrigation types.
- Medians and interquartile ranges (IQRs) are similar, suggesting stable environmental conditions.

## **6. Yields by Irrigation Type**
- Significant variability in yields, with numerous outliers exceeding 100,000 across all irrigation types.
- "Spray" irrigation shows the least variability in yields compared to "Drip" and "Basin."

## **7. Price by Irrigation Type**
- Price data shows minimal variation across irrigation types, with no significant outliers.
- Medians and interquartile ranges (IQRs) are consistent across "Drip," "Basin," and "Spray."

---

## **Key Insights**
1. **Outliers**:
   - Outliers are prevalent in "Area" and "Yields" datasets across all irrigation types.
2. **Uniformity**:
   - "Humidity" and "Rainfall" data exhibit consistent patterns across irrigation types.
3. **Variability**:
   - Significant variability is observed in "Temperature" and "Area" based on irrigation types, with "Spray" showing distinct trends in temperature.

---

This analysis highlights key patterns and anomalies across th datasets for different irrigation types.
"""

column = df.select_dtypes(include = 'number').columns
plt.subplots(4,2, figsize = (25,25))
for idx, col in tqdm(enumerate(column), total = len(column), desc = 'plotting...:'):
    plt.subplot(4,2,idx + 1)
    sns.boxplot(x='Irrigation', y=col, data=df)
    plt.tick_params(axis = 'x', labelsize = 16)
    plt.tick_params(axis = 'y', labelsize = 16)
    plt.title(f'Box Plot of {col} by Irrigation', fontsize = 22, fontweight = 'bold')
    plt.xlabel('Irrigation', fontsize = 16, fontweight = 'bold')
    plt.ylabel(col, fontsize = 16, fontweight = 'bold')
plt.savefig(col)
plt.subplots_adjust(left=0.1, bottom=0.1, right=0.9, top=0.9, wspace=0.15, hspace=7.5)
plt.tight_layout()
plt.show()

"""# Analysis of Box Plots by Crops

## **1. Year by Crops**
- Year data is consistent across all crops, with stable medians.
- There are no significant outliers, indicating uniform planting trends over the years.

## **2. Area by Crops**
- Significant variability in area across crops, with some crops showing extreme outliers exceeding 50,000.
- Central values for area vary slightly across crops.

## **3. Rainfall by Crops**
- Rainfall is tightly clustered around the median for most crops.
- Minor outliers exist below 1,000 for a few crops.

## **4. Temperature by Crops**
- Temperature distributions vary widely across crops.
- Certain crops exhibit high outliers above 200, indicating different climatic requirements.

## **5. Humidity by Crops**
- Humidity levels are consistently distributed across crops, with no significant outliers.
- Medians are close for all crops, suggesting similar environmental conditions.

## **6. Yields by Crops**
- Yields show substantial variability, with numerous outliers exceeding 100,000 for many crops.
- Some crops have tightly clustered yield values, indicating consistent productivity.

## **7. Price by Crops**
- Prices are relatively consistent across crops, with no significant outliers.
- Medians and interquartile ranges (IQRs) are similar across all crops.

---

## **Key Insights**
1. **Outliers**:
   - Outliers are prevalent in "Area" and "Yields" datasets for many crops.
2. **Uniformity**:
   - "Humidity" and "Rainfall" data exhibit consistent patterns across all crops.
3. **Variability**:
   - Significant variability is observed in "Temperature" and "Area" based on crop type, with notable differences in climatic and spatial requirements.

---

This analysis highlights key patterns and anomalies across the datasets for different crops.

"""

column = df.select_dtypes(include = 'number').columns
plt.subplots(4,2, figsize = (25,25))
for idx, col in tqdm(enumerate(column), total = len(column), desc = 'plotting...:'):
    plt.subplot(4,2,idx + 1)
    sns.boxplot(x='Crops', y=col, data=df)
    plt.tick_params(axis = 'x', labelsize = 16)
    plt.tick_params(axis = 'y', labelsize = 16)
    plt.title(f'Box Plot of {col} by Crops', fontsize = 22, fontweight = 'bold')
    plt.xlabel('Crops', fontsize = 16, fontweight = 'bold')
    plt.ylabel(col, fontsize = 16, fontweight = 'bold')
    plt.xticks(rotation=45)
plt.savefig(col)
plt.subplots_adjust(left=0.1, bottom=0.1, right=0.9, top=0.9, wspace=0.15, hspace=7.5)
plt.tight_layout()
plt.show()

"""# Analysis of Box Plots by Season

## **1. Year by Season**
- Year data is consistent across all seasons, with stable medians.
- There are no significant outliers, indicating uniform planting trends over the years.

## **2. Area by Season**
- Significant variability in area across seasons, with extreme outliers exceeding 50,000 for all seasons.
- Central values for area are relatively similar across seasons.

## **3. Rainfall by Season**
- Rainfall is tightly clustered around the median for all seasons.
- Minor outliers exist below 1,000 for each season.

## **4. Temperature by Season**
- "Rabi" season shows lower temperature values with minimal variability.
- "Kharif" and "Zaid" seasons show higher temperatures, with outliers extending above 200.

## **5. Humidity by Season**
- Humidity levels are consistently distributed across all seasons, with no significant outliers.
- Medians are close for all seasons, indicating stable environmental conditions.

## **6. Yields by Season**
- Yields show substantial variability, with numerous outliers exceeding 100,000 across all seasons.
- "Rabi" season appears to have slightly lower yield variability compared to others.

## **7. Price by Season**
- Prices are relatively consistent across seasons, with no significant outliers.
- Medians and interquartile ranges (IQRs) are similar for "Kharif," "Zaid," and "Rabi" seasons.

---

## **Key Insights**
1. **Outliers**:
   - Outliers are prevalent in "Area" and "Yields" datasets for all seasons.
2. **Uniformity**:
   - "Humidity" and "Rainfall" data exhibit consistent patterns across seasons.
3. **Variability**:
   - Significant variability is observed in "Temperature" and "Area" based on the season, with distinct trends in "Rabi" compared to "Kharif" and "Zaid."

---

This analysis highlights key patterns and anomalies across the datasets for different seasons.

"""

columnseason = df.select_dtypes(include = 'number').columns
plt.subplots(4,2, figsize = (25,25))
for idx, col in tqdm(enumerate(columnseason), total = len(column), desc = 'plotting...:'):
    plt.subplot(4,2,idx + 1)
    sns.boxplot(x='Season', y=col, data=df)
    plt.tick_params(axis = 'x', labelsize = 16)
    plt.tick_params(axis = 'y', labelsize = 16)
    plt.title(f'Box Plot of {col} by Season', fontsize = 22, fontweight = 'bold')
    plt.xlabel('Season', fontsize = 16, fontweight = 'bold')
    plt.ylabel(col, fontsize = 16, fontweight = 'bold')
plt.savefig(col)
plt.subplots_adjust(left=0.1, bottom=0.1, right=0.9, top=0.9, wspace=0.15, hspace=7.5)
plt.tight_layout()
plt.show()

"""# Analysis of Bar Plots by Location

## **1. Year by Location**
- Year data is evenly distributed across all locations.
- There is no variation, indicating uniform trends.

## **2. Area by Location**
- Most locations have consistent area values, but one location exhibits a significantly lower area.
- This disparity highlights a unique characteristic of that specific location.

## **3. Rainfall by Location**
- Rainfall levels are nearly identical across locations.
- No noticeable variations suggest similar environmental conditions.

## **4. Temperature by Location**
- Temperature values vary slightly across locations, with some locations showing higher temperatures.
- This could reflect minor regional climatic differences.

## **5. Humidity by Location**
- Humidity is uniformly distributed across all locations.
- Consistency indicates similar environmental conditions across regions.

## **6. Yields by Location**
- Most locations exhibit similar yield levels, but a few show lower yields.
- These variations might be due to soil, irrigation, or other local factors.

## **7. Price by Location**
- Prices are uniform across locations, with no significant variation.
- This consistency suggests stable market conditions.

---

## **Key Insights**
1. **Uniformity**:
   - "Rainfall," "Humidity," and "Price" show uniform trends across locations, reflecting consistent environmental and economic conditions.
2. **Variability**:
   - Slight variations in "Temperature" and "Yields" may indicate regional differences in climatic or agricultural practices.
3. **Anomalies**:
   - One location with a significantly lower "Area" stands out, warranting further investigation.

---

This analysis highlights key patterns and anomalies across the datasets for different locations.

"""

column = df.select_dtypes(include = 'number').columns
plt.subplots(4,2, figsize = (25,25))
for idx, col in tqdm(enumerate(column), total = len(column), desc = 'plotting...:'):
    plt.subplot(4,2,idx + 1)
    plt.bar(x=df['Location'], height=df[col], color = 'skyblue')
    plt.tick_params(axis = 'x', labelsize = 16)
    plt.tick_params(axis = 'y', labelsize = 16)
    plt.title(f'Bar plot of {col} by Location', fontsize = 22, fontweight = 'bold')
    plt.xlabel('Location', fontsize = 16, fontweight = 'bold')
    plt.ylabel(col, fontsize = 16, fontweight = 'bold')
    plt.xticks(rotation=45)
plt.savefig(col)
plt.subplots_adjust(left=0.1, bottom=0.1, right=0.9, top=0.9, wspace=0.15, hspace=7.5)
plt.tight_layout()
plt.show()

columns = df.columns.difference(['Year'])
i = 0
while i < 6:
    fig = plt.figure(figsize=(25,6))
    plt.subplot(1,2,1)
    sns.countplot(x = columns[i], data = df, color = 'blue')
    plt.xticks(rotation = 90)

    i+=1
    plt.subplot(1,2,2)
    sns.countplot(x = columns[i], data = df, color = 'gray')
    plt.xticks(rotation = 90)

    i+=1
    plt.show()

plt.figure(figsize=(20,20))
cols = df.columns
sns.pairplot(df[cols],
            hue='price')
plt.subplots_adjust(top=0.95, bottom=0.05, hspace=0.2)
plt.suptitle('Scatter plot features',fontweight = 20, fontsize = 16)
plt.show()

"""# Analysis of Scatter Plots by Price

## **1. Year vs. Price**
- Price remains fairly consistent across years.
- There is no noticeable trend or relationship between year and price, suggesting stability over time.

## **2. Area vs. Price**
- A weak positive correlation is observed; larger areas tend to have higher prices.
- Some clustering is seen at lower area values with varying price ranges.

## **3. Rainfall vs. Price**
- Prices appear relatively consistent across rainfall levels, indicating no significant dependency.
- A few minor clusters suggest localized patterns but no clear trend.

## **4. Temperature vs. Price**
- Prices show a slight pattern of higher values at specific temperature ranges, especially around lower temperatures.
- Outliers at higher temperature values indicate potential exceptions.

## **5. Humidity vs. Price**
- Humidity levels have no clear influence on price, as prices are spread uniformly across the humidity range.
- No significant correlation is detected.

## **6. Yields vs. Price**
- A weak positive relationship is observed; higher yields are generally associated with higher prices.
- Significant clustering at lower yield values with varying prices.

## **7. Price vs. Price**
- This plot likely represents price consistency or acts as a reference baseline.

---

## **Key Insights**
1. **Correlations**:
   - Weak positive correlations exist between price and both area and yield, suggesting slight dependencies.
2. **Independence**:
   - Variables like year, rainfall, humidity, and temperature show no significant relationship with price, indicating independence.
3. **Clustering**:
   - Clusters are observed in some plots, such as area, yields, and rainfall, indicating localized patterns.

---

This analysis highlights the relationships (or lack thereof) between price and various factors in the dataset.

"""

columnprice = df.select_dtypes(include = 'number').columns
plt.subplots(4,2, figsize = (25,25))
for idx, col in tqdm(enumerate(columnprice), total = len(column), desc = 'plotting...:'):
    plt.subplot(4,2,idx + 1)
    plt.scatter(x=col, y='price', data=df)
    plt.tick_params(axis = 'x', labelsize = 16)
    plt.tick_params(axis = 'y', labelsize = 16)
    plt.title(f'Scatter Plot of {col} by price', fontsize = 22, fontweight = 'bold')
    plt.xlabel(col, fontsize = 16, fontweight = 'bold')
    plt.ylabel('price', fontsize = 16, fontweight = 'bold')
plt.savefig(col)
plt.subplots_adjust(left=0.1, bottom=0.1, right=0.9, top=0.9, wspace=0.15, hspace=7.5)
plt.tight_layout()
plt.show()

"""# Analysis of Histograms with KDE

## **1. Year**
- The distribution shows a peak around 2004, indicating a concentration of records in that year.
- A gradual decline is observed from 2004 to 2018, with fewer records in later years.

## **2. Area**
- The distribution is heavily right-skewed, with most values concentrated below 10,000.
- A few extreme values beyond 40,000 are observed, likely outliers.

## **3. Rainfall**
- The data exhibits a bimodal distribution, with peaks around 500 and 3,500.
- This suggests two distinct groups based on rainfall levels.

## **4. Temperature**
- The distribution is heavily skewed to the left, with most values below 75.
- A small number of outliers extend beyond 200.

## **5. Humidity**
- The distribution is approximately normal, with a peak around 55.
- Slight variations suggest consistent humidity levels across the dataset.

## **6. Yields**
- A right-skewed distribution is observed, with most values concentrated below 100,000.
- Some extreme values beyond 500,000 indicate outliers.

## **7. Price**
- The distribution is slightly bimodal, with peaks around 50,000 and 200,000.
- This suggests the presence of two groups or pricing strategies in the dataset.

---

## **Key Insights**
1. **Skewness**:
   - Variables like "Area," "Yields," and "Temperature" exhibit significant skewness, indicating data clustering toward lower values.
2. **Bimodal Distributions**:
   - Rainfall and price show bimodal distributions, suggesting distinct groupings in the data.
3. **Normality**:
   - Humidity follows a nearly normal distribution, indicating consistent environmental conditions.

---

This analysis highlights the overall distribution patterns and key insights from the dataset variables.

"""

columnss = df.select_dtypes(include = ['number']).columns
plt.subplots(4,2, figsize = (25,20))
for idx,col in enumerate(columnss):
    plt.subplot(4,2,idx + 1)
    sns.histplot(df[col], bins=15, linewidth=0.5, edgecolor="white",
            kde = True, color = 'blue', alpha = 0.5)
    #cumulative = True
    #rug = True
    plt.tick_params(axis = 'x', labelsize = 20)
    plt.tick_params(axis = 'y', labelsize = 20)
    plt.title(col, fontsize = 20)
    plt.xlabel(col, fontsize = 20)
plt.savefig(col)
plt.tight_layout()
plt.show()

"""# Analysis of Pie Charts

## **1. Location Feature**
- The distribution is dominated by a few locations, such as **Gulbarga (25.3%)** and **Hassan (16.0%)**.
- Smaller contributions are observed from locations like Kodagu and Raichur, each contributing less than 8%.

## **2. Soil Type Feature**
- **Alluvial soil** forms the largest category, contributing **14.8%**, followed by **Loam (9.1%)** and **Laterite (8.5%)**.
- Other soil types such as **Red, Sandy, and Black soils** show smaller but significant contributions.

## **3. Irrigation Feature**
- **Drip irrigation** is the most commonly used method, accounting for **41.5%**.
- **Basin (30.7%)** and **Spray (27.9%)** irrigation methods are almost equally distributed.

## **4. Crops Feature**
- **Coconut** is the dominant crop, representing **46.2%**.
- Other crops like **Groundnut, Ginger, and Tea** have smaller but noteworthy contributions, with each around **4-9%**.

## **5. Season Feature**
- The **Rabi season** dominates, covering **55.2%**, followed by **Zaid (25.6%)** and **Kharif (19.2%)**.
- This indicates the prevalence of Rabi crops in the dataset.

---

## **Key Insights**
1. **Dominant Categories**:
   - **Location**: Gulbarga and Hassan are significant contributors.
   - **Soil Type**: Alluvial soil is the most common.
   - **Irrigation**: Drip irrigation dominates.
   - **Crops**: Coconut is the leading crop.
   - **Season**: Rabi season is the most prevalent.

2. **Diversity**:
   - The dataset shows diversity in locations, soil types, and crops, although some categories dominate.

3. **Balance**:
   - Irrigation methods and soil types are relatively balanced, with no single category being overly dominant.

---

This analysis highlights the distribution of key features and their relative contributions within the dataset.

"""

columns_to_plot = df.select_dtypes(include = ['object']).columns
num_cols = 2
num_rows = (len(columns_to_plot) + num_cols - 1) // num_cols  # Calculate number of rows based on columns to plot

fig, axes = plt.subplots(num_rows, num_cols, figsize=(30, 35))
axes = axes.flatten()  #

for i, column in enumerate(columns_to_plot):
    column_values = df[column].value_counts()  # Value counts for the current column
    labels = column_values.index.tolist()
    sizes = column_values.values.tolist()

    colors = ['red', 'blue', 'green', 'orange', 'purple'][:len(labels)]  # Adjust colors based on labels
    explode = [0.1] + [0] * (len(labels) - 1)  # This creates a list of zeros with a length equal to the number of remaining slices, Each 0 means the corresponding slice will not be exploded or offset.

    ax = axes[i]
    ax.pie(
        sizes,
        labels=labels,
        explode=explode,
        colors=colors,
        autopct='%1.1f%%',
        shadow=True,
        startangle=140,
        textprops={'fontsize': 16, 'fontweight': 'bold'}
    )
    ax.set_title(f'{column.capitalize()} Feature', color='blue', fontsize=20, fontweight='bold')
    plt.savefig(column)
plt.tight_layout()
plt.show()

columnss4 = df.select_dtypes(include='number').columns
plt.subplots(4,2, figsize = (25,25))
for idx, col in tqdm(enumerate(columnss4), total = len(columnss4), desc = 'plotting...:'):
    plt.subplot(4,2,idx + 1)
    plt.plot(df['Year'],df2[col], marker = 'o', color = 'gray')
        #cumulative = True
        #rug = True
    plt.tick_params(axis = 'x', labelsize = 20)
    plt.tick_params(axis = 'y', labelsize = 20)
    plt.title(col, fontsize = 20)
    plt.ylabel(col, fontsize = 20)
    plt.xlabel('Year', fontsize = 20)
plt.tight_layout()
plt.show()

df.plot(subplots = True, figsize = (25, 20))

df.isna().sum()

first_nan_index = df[df['Soil type'].isna()].index[29]
df.reset_index(inplace = True, drop = True)
result = df.loc[3070:first_nan_index, :]
result

df.head(2)

df.columns

"""# Analysis of the Effects of Numerical Variables on Price

## **1. Area**
- A positive relationship is observed between area and price; larger areas tend to have higher prices.
- There is clustering at lower area values with varying prices, indicating that smaller areas may have a wider price range.

## **2. Rainfall**
- Rainfall has minimal impact on price, as prices remain evenly distributed across rainfall levels.
- No clear trend or pattern is observed.

## **3. Temperature**
- Higher temperatures appear to have a slight association with increased price.
- However, the majority of data points are concentrated at lower temperature values with varying prices.

## **4. Yields**
- Yields exhibit a weak positive correlation with price; higher yields generally correspond to higher prices.
- A notable number of outliers with high yield values suggest exceptional cases.

## **5. Humidity**
- Humidity does not show a clear influence on price, as prices are evenly distributed across humidity levels.
- There is no observable trend or correlation.

---

## **Key Insights**
1. **Positive Correlations**:
   - Variables such as area and yield show weak positive correlations with price, suggesting that larger areas and higher yields might contribute to higher prices.
   
2. **Independence**:
   - Rainfall and humidity appear to have little to no effect on price, indicating independence from these variables.

3. **Outliers**:
   - Extreme values in yield and area highlight potential outliers or exceptional cases that may
need further investigation.

---

This analysis provides an overview of how numerical variables influence price in the dataset.

"""

# Analysis of Features by simultaneously displaying them in one plot
df_col = {'Area':'blue','Rainfall':'orange','Temperature':'green','yeilds':'black', 'Humidity':'yellow'}
plt.figure(figsize=(8,6)) # (you can use , dpi=100)
for col, color in df_col.items():
    sns.scatterplot(data=df, x=col, y='price', label=f'{col}', color=color)

#sns.lineplot(data=df, x='World_Rank', y='Score', label='World_Rank', color='black')
plt.title('The effects of all numerical variables on Price'
            , fontsize=14, fontweight='bold')
plt.legend()
plt.xlabel('Variables')
plt.savefig('a.jpg')
plt.tight_layout()
plt.show()

"""# Analysis of Metrics Across Locations

## **1. Hassan**
- **Price**: Among the highest values, indicating high market activity or demand.
- **Area**: Comparatively moderate.
- **Rainfall, Temperature, and Humidity**: Balanced and aligned with averages.

## **2. Gulbarga**
- **Price**: Highest among all locations, suggesting significant market value or agricultural productivity.
- **Area**: Largest across locations, indicating extensive agricultural land.
- **Rainfall and Humidity**: Moderate values, likely contributing to its productivity.

## **3. Mangalore**
- **Price**: Moderate, indicating average market value.
- **Area**: High but less than Gulbarga.
- **Rainfall and Humidity**: Relatively high, contributing to its agricultural suitability.

## **4. Chikmagalur**
- **Price and Area**: Comparable to Mangalore.
- **Rainfall**: Slightly higher, suggesting potential for rainfall-dependent crops.
- **Humidity**: Moderate levels, conducive to specific crop types.

## **5. Mysuru, Kodagu, and Other Locations**
- **Price**: Consistent across locations with no extreme outliers.
- **Area**: Moderate, indicating uniform land distribution.
- **Rainfall and Temperature**: Balanced across locations, supporting diverse crops.

## **6. Davangere and Bangalore**
- **Price**: Lowest among all locations.
- **Area**: Minimal, indicating limited agricultural activity.
- **Rainfall, Temperature, and Humidity**: Lower levels, potentially impacting productivity.

---

## **Key Insights**
1. **Gulbarga's Dominance**:
   - Gulbarga stands out with the highest price and area values, suggesting its importance in agricultural output or market value.

2. **Location Variability**:
   - Significant variations in area and price exist among locations, with rainfall and temperature contributing to agricultural patterns.

3. **Balanced Metrics**:
   - Most locations maintain balanced values for rainfall, humidity, and temperature, creating opportunities for diverse agricultural practices.

4. **Davangere and Bangalore's Outliers**:
   - These locations show limited values across all metrics, highlighting potential underutilization or alternative usage of land.

---

This analysis highlights the comparative metrics across locations, emphasizing dominant areas and areas with potential for improvement.

"""

location_counts = df['Location'].value_counts()
locations = location_counts.index

categories = ['Area', 'Rainfall', 'Temperature','yeilds', 'Humidity','price']
colors = ['lightyellow', 'orange', 'lightgray','blue','red','skyblue']

bar_width = 0.2
x = np.arange(len(locations))

fig, ax = plt.subplots(figsize=(12, 8))

for i, category in enumerate(categories):
    if category in df.columns:
        ax.bar(x + i * bar_width, df.groupby('Location')[category].sum().reindex(locations),
               bar_width, label=category, color=colors[i], edgecolor='black')

ax.yaxis.set_major_locator(MaxNLocator(nbins = 40))
ax.set_xticks(x + bar_width * (len(categories) - 1) / 2)
ax.set_xticklabels(locations, rotation=45, ha='right')
ax.set_ylabel("Values")
ax.set_title("Comparison of Metrics Across Locations")
ax.legend(title="Metrics")
plt.savefig('b.jpg')
plt.tight_layout()
plt.show()

"""# Analysis of Temperature and Humidity Across Locations

## **1. Hassan and Gulbarga**
- **Temperature**: Gulbarga has the highest temperature levels among all locations, followed closely by Hassan.
- **Humidity**: These locations also have relatively high humidity levels, indicating balanced climatic conditions.

## **2. Mangalore and Chikmagalur**
- **Temperature**: Moderate temperature levels, supporting diverse agricultural practices.
- **Humidity**: High humidity levels, likely due to proximity to coastal or high-altitude regions.

## **3. Madikeri and Raichur**
- **Temperature**: Slightly higher than average, contributing to specific crop suitability.
- **Humidity**: Balanced levels, creating favorable growing conditions.

## **4. Mysuru, Kodagu, and Kasaragodu**
- **Temperature**: Moderate values, consistent across these regions.
- **Humidity**: Higher levels, which could indicate good conditions for crops requiring moisture.

## **5. Davangere and Bangalore**
- **Temperature**: Among the lowest, indicating relatively cooler conditions.
- **Humidity**: Lower levels, which may limit crop diversity or suitability for certain agricultural practices.

---

## **Key Insights**
1. **Regional Variations**:
   - Locations like Gulbarga and Hassan exhibit the highest temperature and humidity levels, reflecting their climatic dominance.
   - Coastal and high-altitude regions like Mangalore and Chikmagalur show high humidity and moderate temperature, favorable for certain crops.

2. **Outliers**:
   - Bangalore and Davangere show both low temperature and humidity levels, making them stand out compared to other locations.

3. **Agricultural Suitability**:
   - High humidity regions like Mangalore and Kodagu are likely more suited for crops requiring moisture.
   - High-temperature regions like Gulbarga might support heat-tolerant crops.

---

This analysis highlights temperature and humidity variations across locations and their potential impact on agricultural practices.

"""

location_counts = df['Location'].value_counts()
locations = location_counts.index

categories = ['Temperature','Humidity']
colors = ['orange', 'lightgray']

bar_width = 0.15
x = np.arange(len(locations))

fig, ax = plt.subplots(figsize=(12, 8))

for i, category in enumerate(categories):
    if category in df.columns:
        ax.bar(x + i * bar_width, df.groupby('Location')[category].sum().reindex(locations),
               bar_width, label=category, color=colors[i], edgecolor='black')


ax.set_xticks(x + bar_width * (len(categories) - 1) / 2)
ax.set_xticklabels(locations, rotation=45, ha='right')
ax.set_ylabel("Values")
ax.set_title("Comparison of Metrics Across Locations")
ax.legend(title="Metrics")
plt.savefig('c.jpg')
plt.tight_layout()
plt.show()

df.columns

"""# Analysis of Temperature and Humidity Across Years

## **1. 2004**
- Both temperature and humidity values are significantly higher compared to other years.
- This year stands out as an outlier in the dataset.

## **2. 2017 and 2016**
- These years exhibit moderate values of temperature and humidity, slightly higher than other years but significantly lower than 2004.

## **3. 2005 to 2015**
- Temperature and humidity values remain relatively stable during this period, with minor fluctuations.
- There is no drastic variation, indicating consistent climatic conditions.

## **4. 2018 and 2019**
- These years show the lowest values of temperature and humidity, suggesting reduced data entries or changes in climatic conditions.

---

## **Key Insights**
1. **2004 Dominance**:
   - The exceptionally high temperature and humidity values in 2004 make it a clear outlier in the dataset.

2. **Stability**:
   - From 2005 to 2015, temperature and humidity remain consistent, reflecting stable climatic trends over the decade.

3. **Decline in Later Years**:
   - A noticeable decline in both metrics in 2018 and 2019 suggests possible changes in data collection or climatic variations.

---

This analysis highlights temperature and humidity trends over the years, with key outliers and patterns identified.
ial impact on agricultural practices.

"""

year_counts = df['Year'].value_counts()
years = year_counts.index

categories = ['Temperature', 'Humidity']
colors = ['red', 'blue']

bar_width = 0.15
x = np.arange(len(years))

fig, ax = plt.subplots(figsize=(10, 6))

for i, category in enumerate(categories):
    if category in df.columns:
        values = df.groupby('Year')[category].sum().reindex(years)
        bars = ax.bar(x + i * bar_width, values,
               bar_width, label=category, color=colors[i], edgecolor='black')

ax.set_xticks(x + bar_width * (len(categories) - 1) / 2)
ax.set_xticklabels(years, rotation=45, ha='right')
ax.set_ylabel("Values")
ax.set_title("Comparison of Metrics Across Years")
ax.legend(title="Summation of each case in each year")
plt.savefig('d.jpg')
plt.tight_layout()
plt.show()

year_counts = df['Year'].value_counts()
years = year_counts.index

categories = ['Rainfall', 'price']
colors = ['red', 'blue']

bar_width = 0.15
x = np.arange(len(years))

fig, ax = plt.subplots(figsize=(10, 6))

for i, category in enumerate(categories):
    if category in df.columns:
        values = df.groupby('Year')[category].sum().reindex(years)
        bars = ax.bar(x + i * bar_width, values,
               bar_width, label=category, color=colors[i], edgecolor='black')

ax.set_xticks(x + bar_width * (len(categories) - 1) / 2)
ax.set_xticklabels(years, rotation=45, ha='right')
ax.set_ylabel("Values")
ax.set_title("Comparison of Metrics Across Years")
ax.legend(title="Summation of each case in each year")
plt.tight_layout()
plt.show()

"""# Analysis of Variables Over the Years

## **1. Area Over the Years**
- The mean area shows some fluctuations across the years, with peaks in certain years like 2010 and 2016.
- A slight decline in mean area is observed towards the later years.

## **2. Rainfall Over the Years**
- Rainfall remains relatively stable throughout the years.
- No significant fluctuations are observed, indicating consistent climatic patterns.

## **3. Temperature Over the Years**
- Temperature shows a slight increasing trend in the earlier years, reaching a peak around 2012.
- A gradual decrease is observed in the later years.

## **4. Yields Over the Years**
- Yields show moderate fluctuations, with higher values in years like 2008 and 2016.
- The trend is relatively stable overall, with no drastic increases or decreases.

## **5. Humidity Over the Years**
- Humidity levels remain consistent across the years, with minor variations.
- This indicates stable environmental conditions for crop production.

## **6. Price Over the Years**
- Price shows fluctuations, with higher values observed around 2010 and 2018.
- The trend suggests periodic increases in market value over time.

---

## **Key Insights**
1. **Consistency**:
   - Variables like rainfall, humidity, and yields remain consistent over the years, indicating stable environmental and agricultural conditions.

2. **Fluctuations**:
   - Area, temperature, and price show noticeable fluctuations, reflecting potential changes in land usage, climatic conditions, or market dynamics.

3. **Trends**:
   - A slight increase in temperature in the earlier years and periodic increases in price highlight potential areas for further exploration.

---

This analysis provides insights into how key variables have changed over the years and their potential implications.

"""

columns_to_plot = ['Area', 'Rainfall', 'Temperature', 'yeilds', 'Humidity', 'price']

fig, axes = plt.subplots(len(columns_to_plot), 1, figsize=(10, 20), sharex=True)
for ax, column in zip(axes, columns_to_plot):
    mean_values = df.groupby('Year')[column].mean()

    ax.bar(mean_values.index, mean_values.values, color='blue', edgecolor='black',width=0.4)
    ax.set_title(f'{column} Over the Years')
    ax.set_ylabel(f'Mean Value of {column}')
    ax.set_xlabel('Year')
plt.savefig(column)
plt.tight_layout()
plt.show()

pio.renderers.default = 'iframe'
fig = px.sunburst(
    df,
    path=['Location','Crops','Irrigation','Season'],
    color='price',
    color_continuous_midpoint=np.average(df['price']),
    color_continuous_scale='blues',  # Corrected spelling
    width = 900,
    height = 900
)
fig.update_layout(margin=dict(t=40, l=0, r=0, b=0))
fig.show()

